### ISSUE TITLE
Examples of usage

### ISSUE THREAD

**Issue by ReinsBrain** [realtymaps/dbsync#8]
Hi,

This is probably not a great place to reach out but I couldn't find another way to pose a question:

Is there any open source projects in github that are using dbsync? I'm hoping to see an example of it in practice...

Thanks in advance :)

**Comment by zacronos** [comment]
This is the perfect place to reach out -- I like to keep questions (and their answers) public for others to see.

I'm not aware of any other projects that use this.  We use it internally for some non-open projects, and have made this open in case others want to use it.  So, I've got a lot of example usage, but nothing I can share.

In our case, we include it in a startup script so it runs every time the app starts.  Then all you have to do to alter your schema is drop a migration file containing SQL into whatever directory in your project is being scanned by `dbsync`.  If you include that migration file with a PR that makes the code changes to use the new schema, then as soon as your teammates pull your new code and run the app, their db will be updated appropriately.

Do you have any specific questions about recommended usage?

**Comment by ReinsBrain** [comment]
Hi,

Thanks for responding - from your explanation I have a much better sense of how this could be implemented. At startup is a fine place and I'm thinking since I'm leaning on npm quite a bit I might even consider running it pre or postinstall...

Thanks again :)

**Comment by zacronos** [comment]
Great, glad to help.
